### ISSUE TITLE
coach info change

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna#34]
A Message From Pauline Halstead

Reply To: info@abilitiesinmotion.ca

1. I am listed at an instructor on your site. Lots of changes since that listing. Would you kindly change the website and email from www.paddlesandboots.net, info@paddlesandboots.net to www.abilitiesinmotion.ca, info@abilitiesinmotion.ca. We incorporated as a non profit in 2009. I am not able to list my questions: says too long. Please let me know a convenient time to call you. Pauline Halstead Executive Director www.abilitiesinmotion.ca info@abilitiesinmotion.ca

**Comment by salbanese** [comment]
I've made this update
