### ISSUE TITLE
google for non profits set up

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna#38]
1. Add the TXT record below to the DNS configuration for paddlesportsnorthamerica.org.
google-site-verification=4B_LIepUYMkhqIj6c95EvcLSHrlIBFX3HCTnNQKCtBM

Does this option work for you?  They can also do it via a cname record if that's better

-Scott

**Comment by salbanese** [comment]
Hi Scott,

I've set up this txt record.  It could take a day or so to propagate, so if it doesn't work at first try again later. If after 48 hours it's still not working let me know.

**Comment by sfairty** [comment]
Awesome, thanks for getting this one done!

-S.

**Comment by sfairty** [comment]
Seth,

Did you set up the Google Voice account or do you know who did?

-S.

**Comment by salbanese** [comment]
Wasn’t it Bill?

**Comment by sfairty** [comment]
it's not verifying.

you can access the google account directly, they have other alternative
ways to verify

admin.google.com
pna@paddlesportsnorthamerica.org
bodyboatblade

thanks,
Scott

**Comment by salbanese** [comment]
I’ve gotten it to verify.  Do you want me to get email set up while I’m in there?  It will require additional DNS changes.

**Comment by sfairty** [comment]
Yes please

**Comment by salbanese** [comment]
I’ve set this up, and mail is now running through google.  I’ve migrated over the emails from admin@ and info@

to log in to web mail, go to http://mail.paddlesportsnorthamerica.org <http://mail.paddlesportsnorthamerica.org/> 

initial login is the same as whats in the PNA accounts document, but you will be prompted to set a new password when you first log in.  please remember to change the password in PNA accounts to match so other people who need access to that account can get it.

also, if you’ve set up any desktop mail clients or an iPhone or something, you’ll need to change those settings to point to google.  if you need help with that I can point you to documentation.
