### ISSUE TITLE
Addition to top of Documents Page

### ISSUE THREAD

**Issue by ozardjw** [paddlesports-north-america/pna#39]
Hi Seth,
I've created two table for the PNA fee structure we would like to put up at the top of the documents page. Right now is it very difficult to find the fees for various programs - and the Leadership Registration fee is not on our website at all! I created these as basic html tables, so hopefully you would not have to do much formatting to make them look nice on our website. I'm not sure how to send you the html through this site, so I will email the text and tables directly to you.
John

**Comment by salbanese** [comment]
I've added these tables to the documents page
