### ISSUE TITLE
attendance certificates

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna#41]
I received the attendance certificates from the UK and am trying to print FSRT, open water nav etc.

Do you have a copy of the attendance certificate?  It's printing too low on the page.
-Scott

![attendance certificate02232015](https://cloud.githubusercontent.com/assets/9512925/6328571/d0c1e7f8-bb36-11e4-9a09-7fef14806bc8.jpg)
![attendance cert blank01142015](https://cloud.githubusercontent.com/assets/9512925/6328573/d8b7fede-bb36-11e4-863f-dc6a18af051d.jpg)

**Comment by salbanese** [comment]
Scott,

I just did a test and everything lines up perfectly, which likely means there's some printer weirdness going on.

Check your printer settings, see if you have the option to set the paper size to A5. Make sure the printer driver isn't adding any extra margins or anything like that.

let me know what you find.

**Comment by salbanese** [comment]
I noticed the font on the incorrect one you gave me is larger than when I print it as well.  Make sure your printer driver isn't scaling it at all.  That could be what's causing the problems.
