### ISSUE TITLE
email issue

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna#42]
Seth,

The google email is set up but I can't figure out how to get the info@ emails there.  emails also aren't coming into the hover email (which I assumed is desireable)
-S.

**Comment by paddlesports-north-america** [comment]
Hey Scott,

I tested out the login, works fine.  Info is in the PNA accounts document. 

do you need a link to the doc?

Yes, hover mail is no longer being used.

**Comment by salbanese** [comment]
I assume you'v got this sorted now?
