### ISSUE TITLE
Jeffrey Forseth

### ISSUE THREAD

**Issue by ozardjw** [paddlesports-north-america/pna#54]
Something's messed up in the database with Jeffery Forseth (PNA number 209). When a download the database he shows up with a 2010 expiration year. He is actually entered twice in one of the tables - one is incorrect and one look good. If you click 'View' on his name and then 'Memberships' in the right hand column he comes up with two entries (#147 and #153). 153 looks good.

**Comment by paddlesports-north-america** [comment]
Under each members ‘Memberships’ page, it will add a new entry every time they renew their membership, so Jeffery had a membership that expired in 2010, and then renewed on march 17 2015.  The 2010 expiration date in the download is related to the previous issue you filed ( #53 ) which I will be pushing a fix for shortly
