### ISSUE TITLE
Update to text on Membership and Documents pages

### ISSUE THREAD

**Issue by ozardjw** [paddlesports-north-america/pna#55]
Seth,
On the Membership page please replace:

"Please make checks payable to Paddlesports North America."

and on the Documents page please replace:

"All payments to be made in U.S. dollars. PNA currently accepts payment via check or PayPal account. Make checks payable to: Paddlesports North America. PayPal is preferred for non-U.S. bank transactions, even if funds are payable in U.S. dollars. If you would like to pay via PayPal please contact PNA for a PayPal invoice."

With:

"Currently, Paddlesports North America will only accept payment via a personal or business check payable in U.S. dollars and drawn on a U.S. bank, or via PayPal’s credit card payment or transfer options.  Please contact us at: info@paddlesportsnorthamerica.org if you would like to receive a PayPal invoice for membership and/or program services. We are investigating other payment mechanisms, and hope to make additional options available in the future.

Make checks payable to: Paddlesports North America. Please do not send cash through the mail!"

**Comment by salbanese** [comment]
This is done
