### ISSUE TITLE
duplication on calendar

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna#57]
I created a new center (maine Island kayak) they are using Greg Paquin to run a 3 star and 4 star in June.  The calendar lists the course both under Maine Island and Kayak Waveology (greg's company)

**Comment by salbanese** [comment]
The calendar is working as expected.  Both sets of courses are actually in the database.  The ones listing Kayak Waveology were created in the DB on March 9th, and the maine island kayak courses were created may 12th.

Just delete the ones you don’t want.
